config/routes.rb
Rails.application.routes.draw do

  resources :links do
    member do
      get 'click'
    end
    resources :comments do
      resources :comments
    end
    resources :votes, :only => [:create]
  end

  resources :users, :except => [:destroy]
  resources :user_sessions, :only => [:new, :create, :destroy]

  root 'links#index'

  get '/tags/:tag' => 'links#index', :as => :tag

end

app/models/link.rb
class Link < ActiveRecord::Base

  has_many :votes
  belongs_to :user
  has_many :taggings
  has_many :tags, :through => :taggings

  validates_presence_of :title, :url

  validates_format_of :url, :with => /\Ahttp(|s):\/\//

  before_validation :add_http

  scope :voted_on, -> { where(:voted => true) }

  def add_http
    unless self.url =~ /\Ahttp(|s):\/\//
      self.url = "http://" + self.url
    end
  end

  def cast_vote(user, value=1)
    vote = Vote.new(value: value, :user => user)
    self.votes << vote
    vote
  end

  def tag_names=(tags)
    tags.split(",").collect{|t| t.strip}.each do |tag|
      this_tag = Tag.find_or_create_by(name: Tag.clean_name(tag))
      self.tags << this_tag
    end
  end

  def tag_names
    self.tags.collect{|t| t.name}.join(", ")
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggings
  has_many :links, :through => :taggings

  validates_uniqueness_of :name

  before_validation :downcase_name,
                    :strip_spaces,
                    :replace_spaces,
                    :strip_punctuation,
                    :strip_trailing_underscores,
                    :remove_double_underscores

  def downcase_name
    self.name = self.name.downcase
  end

  def strip_spaces
    self.name = self.name.strip
  end

  def replace_spaces
    self.name = self.name.gsub(" ", "_")
  end

  def strip_punctuation
    self.name = self.name.gsub(/\W/, "")
  end

  def strip_trailing_underscores
    self.name = self.name.gsub(/(_+)$/, "")
  end

  def remove_double_underscores
    self.name = self.name.gsub(/(_{2,})/, "_")
  end

  def self.clean_name(name)
    tag = Tag.new(name: name)
    tag.downcase_name
    tag.strip_spaces
    tag.replace_spaces
    tag.strip_punctuation
    tag.strip_trailing_underscores
    tag.remove_double_underscores
    tag.name
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base

  belongs_to :link
  belongs_to :tag

  validates_presence_of :link, :tag

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.login_field :email
  end

  has_many :links
  has_many :votes
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base


end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :link
  belongs_to :user

  validates :link_id, uniqueness: {scope: :user_id, message: "You can only vote for a link once."}

  after_save :update_link_totals

  def update_link_totals
    link.voted = true
    link.vote_total = link.votes.sum(:value)
    link.save!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user_session, :current_user
  before_action :current_user

  private
  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def require_user
    unless @current_user
      flash[:danger] = "You need to be logged in to do that."
      redirect_to root_url
    end
  end

  def require_no_user
    if @current_user
      flash[:warning] = "You're already logged in and good to go."
      redirect_to root_url
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index:get
  end

  def show:get
  end

  def create:post
  end

  def edit:get
  end

  def update:patch
  end

  def destroy:delete
  end

  def new:get
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :require_user, :only => [:new, :create, :edit, :update]
  before_action :check_if_current_user_is_owner, :only => [:edit, :update]

  def index
    if params[:tag]
      @tag = Tag.find_by_name(params[:tag])
      @links = @tag.links.order("vote_total DESC").page(params[:page] || 1).per(10)
    else
      @links = Link.order("vote_total DESC").page(params[:page] || 1).per(10)
    end
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    @link.user = @current_user
    if @link.save
      flash[:success] = "Wahoo! You've submitted an awesome new link!"
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @link.update(link_params)
      redirect_to root_url
    else
      render "edit"
    end
  end

  def click
    @link = Link.find(params[:id])
    @link.votes.create
    redirect_to @link.url
  end


  private

  def link_params
    params.require(:link).permit(:title, :url, :summary, :tag_names)
  end

  def check_if_current_user_is_owner
    @link = Link.find(params[:id])
    unless @link.user == @current_user
      flash[:danger] = "That's not your link, bub!"
      redirect_to root_url
    end
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_user, only: [:new, :create]
  before_action :require_user, only: [:destroy]

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_user, :only => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @link = Link.find(params[:link_id])
    if params[:downvote]
      value = -1
    else
      value = 1
    end
    vote = @link.cast_vote(@current_user, value)
    unless vote.persisted?
      flash[:warning] = vote.errors.first.last
    end
    redirect_to :back
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/create:post.html.erb
<h1>Comments#create:post</h1>
<p>Find me in app/views/comments/create:post.html.erb</p>

app/views/comments/destroy:delete.html.erb
<h1>Comments#destroy:delete</h1>
<p>Find me in app/views/comments/destroy:delete.html.erb</p>

app/views/comments/edit:get.html.erb
<h1>Comments#edit:get</h1>
<p>Find me in app/views/comments/edit:get.html.erb</p>

app/views/comments/index:get.html.erb
<h1>Comments#index:get</h1>
<p>Find me in app/views/comments/index:get.html.erb</p>

app/views/comments/new:get.html.erb
<h1>Comments#new:get</h1>
<p>Find me in app/views/comments/new:get.html.erb</p>

app/views/comments/show:get.html.erb
<h1>Comments#show:get</h1>
<p>Find me in app/views/comments/show:get.html.erb</p>

app/views/comments/update:patch.html.erb
<h1>Comments#update:patch</h1>
<p>Find me in app/views/comments/update:patch.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redditor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: "alert alert-#{name}" %>
    <% end %>
    <div class="col-xs-10">
      <%= yield %>
    </div>
    <div class="col-xs-2">
      <% if @current_user %>
        <h6>Howdy, <%= @current_user.name %></h6>
        <%= link_to "New Link", new_link_path, :class => "btn btn-large btn-primary" %>
        <%= link_to "Log out", user_session_path(@current_user), :method => :delete, :class => "btn btn-large btn-danger" %>
      <% else %>
        <%= link_to "Log in", new_user_session_path, :class => "btn btn-large btn-primary" %>
        <%= link_to "Sign up", new_user_path, :class => "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/links/edit.html.erb
<h1>Edit "<%= @link.title %>"</h1>
<%= render "shared/link_form" %>

app/views/links/index.html.erb
<%= paginate @links %>

<% @links.each do |link| %>
  <div class="row">
    <div class="col-xs-3">
      <% if @current_user %>
        <%= button_to "+1", link_votes_path(link), :class => "btn btn-primary" %>
      <% end %>
      <h6><%= link.vote_total %></h6>
      <% if @current_user %>
        <%= button_to "-1", link_votes_path(link, :downvote => true), :class => "btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-xs-9">
      <h3><%= link_to link.title, click_link_path(link) %></h3>
      <%= simple_format(link.summary) %>
      <p class="meta">Submitted by: <%= link.user.name %><%= " | #{link_to "Edit this link", edit_link_path(link)}".html_safe if @current_user == link.user %></p>
      <% if link.tags.any? %>
        <p class="tags">Tagged with: <%= link.tags.collect{|t| link_to t.name, tag_path(t.name)}.join(", ").html_safe %></p>
      <% end %>
    </div>
  </div>
<% end %>

<%= paginate @links %>

app/views/links/new.html.erb
<h1>New link</h1>
<%= render "shared/link_form" %>

app/views/shared/_link_form.html.erb
<% if @link.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

    <ul>
    <% @link.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for(@link) do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, :class => "form-control", :rows => 4 %>
  </div>
  <div class="form-group">
    <%= f.label :tags %>
    <%= f.text_field :tag_names, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save" %>
  </div>

<% end %>

app/views/user_sessions/new.html.erb
<%= form_for @user_session do |f| %>
  <% if @user_session.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited:</h2>
    <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <%= f.label :email %><br />
  <%= f.text_field :email %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.submit "Login" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= bootstrap_form_for @user do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :username %>
  <%= f.email_field :email %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create" %>
<% end %>